//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csharp_entityframework_my
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_tbl
    {
        public byte id { get; set; }
        public string Kullanıcı { get; set; }
        public string Sifre { get; set; }
    }
}
