//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csharp_entityframework_my
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntityUrunDBEntities : DbContext
    {
        public EntityUrunDBEntities()
            : base("name=EntityUrunDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kategori_tbl> kategori_tbl { get; set; }
        public virtual DbSet<musteri_tbl> musteri_tbl { get; set; }
        public virtual DbSet<satis_tbl> satis_tbl { get; set; }
        public virtual DbSet<urun_tbl> urun_tbl { get; set; }
        public virtual DbSet<admin_tbl> admin_tbl { get; set; }
    
        public virtual ObjectResult<markagetir_Result> markagetir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<markagetir_Result>("markagetir");
        }
    }
}
