//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csharp_entityframework_my
{
    using System;
    using System.Collections.Generic;
    
    public partial class urun_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urun_tbl()
        {
            this.satis_tbl = new HashSet<satis_tbl>();
        }
    
        public int urunid { get; set; }
        public string urunad { get; set; }
        public string urunmarka { get; set; }
        public Nullable<short> stok { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<bool> durum { get; set; }
        public Nullable<int> kategori { get; set; }
    
        public virtual kategori_tbl kategori_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satis_tbl> satis_tbl { get; set; }
    }
}
